@url = http://localhost:3333/api

###
GET {{url}}/user?limit=10&page=1

###
POST {{url}}/user
Content-Type: application/json

{
	"username": "abelfubu",
	"password": "123456",
	"email": "abelfubu@gmail.com"
}

###
POST {{url}}/login
Content-Type: application/json

{
	"password": "123456",
	"email": "abelfubu@gmail.com"
}

