@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNrc2JrbXk2ZTAwMTNud20wczM1bmwxZngiLCJjcmVhdGVkQXQiOiIyMDIxLTA4LTE0VDA5OjIyOjU4LjMxMFoiLCJ1cGRhdGVkQXQiOiIyMDIxLTA4LTE0VDA5OjIyOjU4LjMxMFoiLCJ1c2VybmFtZSI6ImFiZWxmdWJ1IiwiZW1haWwiOiJhYmVsZnVidUBnbWFpbC5jb20iLCJpYXQiOjE2MjkwMTUxMDgsImV4cCI6MTYyOTAxODcwOH0.ofpnBudwmFBtiL1yvzmbe1L_O2dQ0DtjLKX08bBI2Pc

@url = http://localhost:3333/api

###
GET {{url}}/user?limit=10&page=1
Authorization: Bearer {{token}}

###
POST {{url}}/register
Content-Type: application/json

{
	"username": "abelfubu",
	"password": "123456",
	"email": "abelfubu@gmail.com"
}

###
POST {{url}}/login
Content-Type: application/json

{
	"password": "123456",
	"email": "abelfubu@gmail.com"
}

