@url = http://localhost:3333/api/room
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNrc2V5bWp4ejAwMDBsb3VsdjIwa2p4dmkiLCJjcmVhdGVkQXQiOiIyMDIxLTA4LTE2VDE4OjE3OjUzLjAxNVoiLCJ1cGRhdGVkQXQiOiIyMDIxLTA4LTE2VDE4OjE3OjUzLjAxNVoiLCJ1c2VybmFtZSI6ImFiZWxmdWJ1IiwiZW1haWwiOiJhYmVsZnVidUBnbWFpbC5jb20iLCJpYXQiOjE2MjkzMDQzMjYsImV4cCI6MTYyOTMwNzkyNn0.VLRuCaVZ3c0yOfpaX8Qa1JZpagLKaHNS9A7AuSr4zSY
###
GET {{url}}
Authorization: Bearer {{token}}

###
POST {{url}}
Content-Type: application/json
Authorization: Bearer {{token}}


{
	"name": "Angular",
	"description": "Great angular community"
}

###
GET {{url}}/02

###
DELETE {{url}}/4

###
PATCH {{url}}/ckshpqoid0013qwulv4cnih5u/user
Authorization: Bearer {{token}}

###
DELETE {{url}}/ckshpqoid0013qwulv4cnih5u/user
Authorization: Bearer {{token}}
