@url = http://localhost:3333/api/room
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNrc2RhMTdvZzAxMzZ6NG0weWo1czc3aHQiLCJjcmVhdGVkQXQiOiIyMDIxLTA4LTE1VDE0OjAxOjQwLjM4NFoiLCJ1cGRhdGVkQXQiOiIyMDIxLTA4LTE1VDE0OjAxOjQwLjM4NFoiLCJ1c2VybmFtZSI6ImFiZWxmdWJ1IiwiZW1haWwiOiJhYmVsZnVidUBnbWFpbC5jb20iLCJpYXQiOjE2MjkwMzc5MDIsImV4cCI6MTYyOTA0MTUwMn0.5-SId0erft89ZfFzmFKRdS9SS86nlPVz1YF5EfJXYQU
###
GET {{url}}
Authorization: Bearer {{token}}

###
POST {{url}}
Content-Type: application/json
Authorization: Bearer {{token}}


{
	"name": "Angular",
	"description": "Great angular community"
}

###
GET {{url}}/02

###
DELETE {{url}}/4

###
PATCH {{url}}/cksdb4e0s0047oom0e2sw8dnk/user
Authorization: Bearer {{token}}

###
DELETE {{url}}/cksdb4e0s0047oom0e2sw8dnk/user
Authorization: Bearer {{token}}
